Repository ApollosProject/apollos-templates, pull requests merged in 2020-10, with the labels that each got.

#186 Makes Encrypting Secrets Easier
  package.json
  scripts/secrets.sh
Labels: ready for review

#185 Renames Android Package
  apollos-church-api/config.yml
  apolloschurchapp/android/app/BUCK
  apolloschurchapp/android/app/build.gradle
  apolloschurchapp/android/app/src/main/AndroidManifest.xml
  apolloschurchapp/android/app/src/main/java/com/differential/apollos/MainActivity.java
  apolloschurchapp/android/app/src/main/java/com/differential/apollos/MainApplication.java
Labels: merge, ready for review

#187 Fix Android Gradle Variables
  apolloschurchapp/android/app/build.gradle
  apolloschurchapp/android/gradle.properties
Labels: merge

#184 Makes Releases Easier
  apollos-church-api/scripts/add-packages.sh
  apolloschurchapp/scripts/add-packages.sh
  package.json
  scripts/add-packages.sh
  scripts/bump.sh
  scripts/update-packages.js
Labels: merge

#188 Simplifies Secrets Script
  apollos-church-api/.env.shared.enc
  apolloschurchapp/.env.shared.enc
  apolloschurchapp/android/app/apollos.keystore.enc
  apolloschurchapp/android/key.json.enc
  package.json
  scripts/secrets.sh
Labels: merge

#189 Fixes Android Deploy
  .github/workflows/deploy-android.yml
Labels: merge

#202 Search feed connected
  apollos-church-api/local.graphql
  apollos-church-api/package.json
  apolloschurchapp/package.json
  apolloschurchapp/src/tabs/discover/Discover.js
  apolloschurchapp/src/tabs/discover/DiscoverFeed/DiscoverFeed.tests.js
  apolloschurchapp/src/tabs/discover/DiscoverFeed/TileContentFeed.js
  apolloschurchapp/src/tabs/discover/DiscoverFeed/__snapshots__/DiscoverFeed.tests.js.snap
  apolloschurchapp/src/tabs/discover/DiscoverFeed/getContentChannels.js
  apolloschurchapp/src/tabs/discover/DiscoverFeed/index.js
  apolloschurchapp/src/tabs/discover/SearchFeed/NoResults.js
  apolloschurchapp/src/tabs/discover/SearchFeed/SearchFeed.tests.js
  apolloschurchapp/src/tabs/discover/SearchFeed/__snapshots__/SearchFeed.tests.js.snap
  apolloschurchapp/src/tabs/discover/SearchFeed/getSearchResults.js
  apolloschurchapp/src/tabs/discover/SearchFeed/index.js
  apolloschurchapp/src/tabs/discover/TileImageItem.js
  apolloschurchapp/src/tabs/discover/__snapshots__/discover.tests.js.snap
  yarn.lock
Labels: merge

#204 Sets up config.yml for action bar feature
  apollos-church-api/config.yml
  apollos-church-api/local.graphql
  apolloschurchapp/src/client/fragmentTypes.json
Labels: merge

#210 fixes discover feed test
  apollos-church-api/local.graphql
  apolloschurchapp/ios/Podfile.lock
  apolloschurchapp/ios/apolloschurchapp.xcodeproj/project.pbxproj
  apolloschurchapp/src/tabs/discover/__snapshots__/discover.tests.js.snap
  apolloschurchapp/src/tabs/discover/discover.tests.js
Labels: merge

#211 Removes Home Feed Test
  apolloschurchapp/src/tabs/discover/__snapshots__/discover.tests.js.snap
  apolloschurchapp/src/tabs/discover/discover.tests.js
  apolloschurchapp/src/tabs/home/Home.js
  apolloschurchapp/src/tabs/home/__snapshots__/home.tests.js.snap
  apolloschurchapp/src/tabs/home/getCampaignContentItem.js
  apolloschurchapp/src/tabs/home/getUserFeed.js
  apolloschurchapp/src/tabs/home/home.tests.js
Labels: merge

#214 Detaches App from API Folder
  apollos-church-api/package.json
  apollos-church-api/scripts/generateLocalSchema.sh
  apolloschurchapp/package.json
  apolloschurchapp/schema.graphql
  apolloschurchapp/src/client/__mocks__/index.js
  yarn.lock
Labels: merge

#212 Cleans up API Scripts
  apollos-church-api/package.json
  yarn.lock
Labels: merge

#217 Fixes Heroku Deploy
  .github/workflows/deploy-api.yml
  README.md
  apollos-church-api/package.json
Labels: merge
