Repository ApollosProject/apollos-templates, pull requests merged in 2020-03, with the labels that each got.

#3 Linting setup
  apollos-church-api/.eslintrc.js
  apollos-church-api/package.json
  apollos-church-api/src/config.js
  apollos-church-api/yarn.lock
  apolloschurchapp/.eslintrc.js
  apolloschurchapp/.graphqlconfig
  apolloschurchapp/package.json
  apolloschurchapp/src/content-single/ContentSingle.js
  apolloschurchapp/src/content-single/DevotionalContentItem/ContentTab.js
  apolloschurchapp/src/content-single/WeekendContentItem/index.js
  apolloschurchapp/src/event/EventConnected.js
  apolloschurchapp/src/tabs/discover/DiscoverFeed/index.js
  apolloschurchapp/yarn.lock
Labels: read-for-review

#8 Removes Scripture Directory
  apolloschurchapp/src/scripture/ScriptureConnected.tests.js
  apolloschurchapp/src/scripture/__snapshots__/ScriptureConnected.tests.js.snap
  apolloschurchapp/src/scripture/getScripture.js
  apolloschurchapp/src/scripture/index.js
Labels: ready for review

#7 Adds Node Version Config
  .nvmrc
  apollos-church-api/.nvmrc
  apolloschurchapp/.nvmrc
  apolloschurchapp/src/user-web-browser/__tests__/__snapshots__/BrowserWithUserCookie.tests.js.snap
Labels: ready for review

#12 Add codecov reporting as a github action
  .github/workflows/tests.yml
Labels: read-for-review

#15 Add mergify to automerge PRs 💥
  .mergify.yml
Labels: ready-for-review

#13 Update README.md
  .mergify.yml
  README.md
Labels: merge, ready-for-review

#16 Fixes potential for client to not link all packages.
  apollos-church-api/scripts/link-packages.js
  apolloschurchapp/scripts/link-packages.js
Labels: ready-for-review

#17 Adds VerticalCardListFeature
  apollos-church-api/config.yml
  apollos-church-api/local.graphql
  apolloschurchapp/src/client/fragmentTypes.json
  apolloschurchapp/src/tabs/home/Features/ActionListFeature/ActionListFeature.stories.js
  apolloschurchapp/src/tabs/home/Features/ActionListFeature/ActionListFeature.tests.js
  apolloschurchapp/src/tabs/home/Features/ActionListFeature/__snapshots__/ActionListFeature.tests.js.snap
  apolloschurchapp/src/tabs/home/Features/ActionListFeature/index.js
  apolloschurchapp/src/tabs/home/Features/VerticalCardListFeature/VerticalCardListFeature.stories.js
  apolloschurchapp/src/tabs/home/Features/VerticalCardListFeature/VerticalCardListFeature.tests.js
  apolloschurchapp/src/tabs/home/Features/VerticalCardListFeature/__snapshots__/VerticalCardListFeature.tests.js.snap
  apolloschurchapp/src/tabs/home/Features/VerticalCardListFeature/index.js
  apolloschurchapp/src/tabs/home/Features/getFeedFeatures.js
  apolloschurchapp/src/tabs/home/Features/index.js
  apolloschurchapp/src/tabs/home/__snapshots__/home.tests.js.snap
  apolloschurchapp/src/tabs/home/getFeedFeatures.js
Labels: merge

#22 Heroku / AppCenter deployment setup
  .gitignore
  Dockerfile
  api_heroku.tf
  apollos-church-api/package.json
  apollos-church-api/yarn.lock
  apolloschurchapp/appcenter-post-clone.sh
  apolloschurchapp/appcenter-pre-build.sh
  example.terraform.tfvars
  heroku.yml
Labels: ready-for-review
