Repository ApollosProject/apollos-templates, pull requests merged in 2020-09, with the labels that each got.

#91 Adds Canary Packages to Dev Process
  apollos-church-api/package.json
  apollos-church-api/scripts/add-packages.sh
  apolloschurchapp/package.json
  apolloschurchapp/scripts/add-packages.sh
  package.json
  yarn.lock
Labels: ready-for-review

#95 Changed Instructions to Recommended Method
  README.md
Labels: ready-for-review

#96 Adds Load Tests
  apollos-church-api/load-tests/Apollos App Testing.jmx
Labels: ready for review

#97 Fixes API builds
  Dockerfile
  README.md
  apollos-church-api/package.json
  apollos-church-api/scripts/add-packages.sh
  apolloschurchapp/package.json
  apolloschurchapp/scripts/add-packages.sh
  package.json
  yarn.lock
Labels: ready for review

#98 Fixes Heroku Docker Deploys
  Dockerfile
Labels: ready for review

#90 Adds Fastlane and Certificates
  .gitignore
  apolloschurchapp/.gitignore
  apolloschurchapp/Gemfile
  apolloschurchapp/Gemfile.lock
  apolloschurchapp/android/app/build.gradle
  apolloschurchapp/android/build.gradle
  apolloschurchapp/android/gradle.properties
  apolloschurchapp/fastlane/Appfile
  apolloschurchapp/fastlane/Fastfile
  apolloschurchapp/fastlane/Matchfile
  apolloschurchapp/fastlane/README.md
  apolloschurchapp/ios/Gemfile
  apolloschurchapp/ios/Gemfile.lock
  apolloschurchapp/ios/apolloschurchapp.xcodeproj/project.pbxproj
  apolloschurchapp/package.json
  apolloschurchapp/src/client/fragmentTypes.json
Labels: ready-for-review

#102 Fixed Fastlane Deploy
  apolloschurchapp/.gitignore
  apolloschurchapp/Gemfile
  apolloschurchapp/Gemfile.lock
  apolloschurchapp/fastlane/Fastfile
  apolloschurchapp/ios/apolloschurchapp-tvOS/Info.plist
  apolloschurchapp/ios/apolloschurchapp-tvOSTests/Info.plist
  apolloschurchapp/ios/apolloschurchapp.xcodeproj/project.pbxproj
  apolloschurchapp/ios/apolloschurchapp/Info.plist
  apolloschurchapp/ios/apolloschurchappTests/Info.plist
Labels: merge

#103 Updates Onesignal
  .gitignore
  apolloschurchapp/.gitignore
  apolloschurchapp/Gemfile
  apolloschurchapp/Gemfile.lock
  apolloschurchapp/android/app/build.gradle
  apolloschurchapp/android/build.gradle
  apolloschurchapp/android/gradle.properties
  apolloschurchapp/fastlane/Appfile
  apolloschurchapp/fastlane/Fastfile
  apolloschurchapp/fastlane/Matchfile
  apolloschurchapp/fastlane/README.md
  apolloschurchapp/ios/Gemfile
  apolloschurchapp/ios/Gemfile.lock
  apolloschurchapp/ios/Podfile.lock
  apolloschurchapp/ios/apolloschurchapp.xcodeproj/project.pbxproj
  apolloschurchapp/package.json
  yarn.lock
Labels: merge

#105 Updates Onesignal
  apolloschurchapp/ios/Podfile.lock
  apolloschurchapp/ios/apolloschurchapp.xcodeproj/project.pbxproj
  apolloschurchapp/package.json
  apolloschurchapp/src/client/fragmentTypes.json
  yarn.lock
Labels: merge

#106 Updates build number based on commits
  apolloschurchapp/fastlane/Fastfile
Labels: ready for review

#108 Steps to deploy Android
  apolloschurchapp/android/gradle.properties
  apolloschurchapp/fastlane/Fastfile
Labels: ready for review

#104 Updates to new church online enpoint
  apollos-church-api/config.yml
  apolloschurchapp/package.json
  yarn.lock
Labels: blocked, ready for review

#107 NodeSingle route and linking fixes
  apollos-church-api/config.yml
  apollos-church-api/local.graphql
  apolloschurchapp/scripts/link-packages.js
  apolloschurchapp/src/content-single/ContentSingle.js
  apolloschurchapp/src/event/EventConnected.js
  apolloschurchapp/src/index.js
  apolloschurchapp/src/node-single/NodeSingle.js
  apolloschurchapp/src/node-single/index.js
  apolloschurchapp/src/tabs/home/Home.js
  apolloschurchapp/src/ui/NavigationHeader/index.js
  package.json
Labels: merge

#109 Deploys Android to Internal, not Alpha
  apolloschurchapp/fastlane/Fastfile
Labels: ready for review

#110 Adds more Android stuff
  apolloschurchapp/Gemfile
  apolloschurchapp/Gemfile.lock
  apolloschurchapp/android/app/build.gradle
  apolloschurchapp/fastlane/Fastfile
  apolloschurchapp/fastlane/README.md
  apolloschurchapp/fastlane/metadata/android/en-US/full_description.txt
  apolloschurchapp/fastlane/metadata/android/en-US/images/featureGraphic.png
  apolloschurchapp/fastlane/metadata/android/en-US/images/icon.png
  apolloschurchapp/fastlane/metadata/android/en-US/images/phoneScreenshots/1_en-US.png
  apolloschurchapp/fastlane/metadata/android/en-US/images/phoneScreenshots/2_en-US.png
  apolloschurchapp/fastlane/metadata/android/en-US/images/phoneScreenshots/3_en-US.png
  apolloschurchapp/fastlane/metadata/android/en-US/short_description.txt
  apolloschurchapp/fastlane/metadata/android/en-US/title.txt
  apolloschurchapp/fastlane/metadata/android/en-US/video.txt
Labels: ready for review

#113 Deploy Android builds as AAB
  apolloschurchapp/fastlane/Fastfile
Labels: merge

#114 Removes Package Versions
  apollos-church-api/package.json
  apolloschurchapp/package.json
Labels: merge

#112 Correctly bumps Android Version Code
  apolloschurchapp/android/app/build.gradle
  apolloschurchapp/fastlane/Fastfile
  apolloschurchapp/fastlane/README.md
Labels: merge

#111 Splits CI
  .github/workflows/linting.yml
  .github/workflows/tests.yml
  .github/workflows/unittest.yml
Labels: ready for review

#115 Updates PR Notice
  .github/pull_request_template.md
Labels: merge

#118 Updates Readme
  README.md
Labels: merge

#117 Deploys to App Store on CI
  .github/workflows/deploy-ios.yml
  apolloschurchapp/fastlane/Fastfile
Labels: merge

#122 Adds Initialization scripts
  README.md
  apollos-church-api/package.json
  apollos-church-api/scripts/init.sh
  apolloschurchapp/package.json
  apolloschurchapp/scripts/init.sh
  package.json
Labels: merge

#124 Authorizes Actions to Deploy
  .github/workflows/deploy-ios.yml
Labels: merge

#123 Triggers CI for all branches
  .github/workflows/linting.yml
  .github/workflows/unittest.yml
Labels: merge

#126 Changes Cert Auth token
  .github/workflows/deploy-ios.yml
Labels: merge

#120 Update from master (DONT SQUASH)
  .github/pull_request_template.md
  .github/workflows/deploy-ios.yml
  .github/workflows/linting.yml
  .github/workflows/tests.yml
  .github/workflows/unittest.yml
  README.md
  apollos-church-api/package.json
  apollos-church-api/scripts/init.sh
  apolloschurchapp/fastlane/Fastfile
  apolloschurchapp/package.json
  apolloschurchapp/scripts/init.sh
  package.json
Labels: blocked, ready for review

#127 Changes Deploy Job Name
  .github/workflows/deploy-ios.yml
Labels: ready for review

#128 Changed to HTTPS Match URL
  apolloschurchapp/fastlane/Matchfile
Labels: ready for review

#129 changed url slightly
  apolloschurchapp/fastlane/Matchfile
Labels: ready for review

#130 Disable fetch cache
  apolloschurchapp/src/client/httpLink.js
Labels: merge, ready for review

#131 Adds environment variables
  .github/workflows/deploy-ios.yml
  apolloschurchapp/fastlane/Matchfile
Labels: ready for review

#133 Fixes workflow file
  .github/workflows/deploy-ios.yml
Labels: ready for review

#132 v1.6.0-beta.0
  .github/workflows/heroku-deploy.yml
  Dockerfile
  apollos-church-api/apollos.json
  apollos-church-api/config.yml
  apollos-church-api/load-tests/Apollos App Testing.jmx
  apollos-church-api/local.graphql
  apollos-church-api/package.json
  apollos-church-api/scripts/add-packages.sh
  apollos-church-api/src/data/index.js
  apolloschurchapp/apollos.json
  apolloschurchapp/package.json
  apolloschurchapp/scripts/add-packages.sh
  apolloschurchapp/scripts/link-packages.js
  apolloschurchapp/src/content-single/ContentSingle.js
  apolloschurchapp/src/event/EventConnected.js
  apolloschurchapp/src/index.js
  apolloschurchapp/src/node-single/NodeSingle.js
  apolloschurchapp/src/node-single/index.js
  apolloschurchapp/src/tabs/home/Home.js
  apolloschurchapp/src/ui/NavigationHeader/index.js
  package.json
  yarn.lock
Labels: ready for review

#135 Changes Heroku Deploy Job name
  .github/workflows/deploy-api.yml
Labels: ready for review

#137 Fixes Linter
  apolloschurchapp/package.json
  apolloschurchapp/src/client/fragmentTypes.json
  yarn.lock
Labels: ready for review

#139 Removes duplicate script
  .github/workflows/heroku-deploy.yml
Labels: ready for review

#140 Fixes canary script
  apollos-church-api/package.json
  apollos-church-api/scripts/add-packages.sh
  apolloschurchapp/package.json
  apolloschurchapp/scripts/add-packages.sh
Labels: blocked, ready for review

#141 Master > Next
  apollos-church-api/package.json
  apollos-church-api/scripts/add-packages.sh
  apolloschurchapp/package.json
  apolloschurchapp/scripts/add-packages.sh
Labels: ready for review

#142 Install Keychain on CI for iOS deploy
  .github/workflows/deploy-ios.yml
Labels: ready for review

#125 Rn63
  apollos-church-api/package.json
  apolloschurchapp/.flowconfig
  apolloschurchapp/.gitignore
  apolloschurchapp/android/app/_BUCK.txt
  apolloschurchapp/android/app/build.gradle
  apolloschurchapp/android/app/src/main/AndroidManifest.xml
  apolloschurchapp/android/app/src/main/java/com/apolloschurchapp/MainApplication.java
  apolloschurchapp/android/app/src/main/java/com/apolloschurchapp/ReactNativeFlipper.java
  apolloschurchapp/android/build.gradle
  apolloschurchapp/android/gradle.properties
  apolloschurchapp/android/gradle/wrapper/gradle-wrapper.properties
  apolloschurchapp/android/gradlew
  apolloschurchapp/android/gradlew.bat
  apolloschurchapp/ios/Podfile
  apolloschurchapp/ios/Podfile.lock
  apolloschurchapp/ios/apolloschurchapp-Bridging-Header.h
  apolloschurchapp/ios/apolloschurchapp.xcodeproj/project.pbxproj
  apolloschurchapp/ios/apolloschurchapp.xcworkspace/xcshareddata/xcschemes/apolloschurchapp.xcscheme
  apolloschurchapp/ios/apolloschurchapp.xcworkspace/xcshareddata/xcschemes/apolloschurchappprod.xcscheme
  apolloschurchapp/ios/apolloschurchapp/AppDelegate.h
  apolloschurchapp/ios/apolloschurchapp/AppDelegate.m
  apolloschurchapp/ios/apolloschurchapp/main.m
  apolloschurchapp/jest.setup.js
  apolloschurchapp/package.json
  apolloschurchapp/scripts/add-packages.sh
  apolloschurchapp/src/content-feed/__snapshots__/content-feed.tests.js.snap
  apolloschurchapp/src/content-single/DevotionalContentItem/__snapshots__/Devotional.tests.js.snap
  apolloschurchapp/src/tabs/discover/DiscoverFeed/__snapshots__/DiscoverFeed.tests.js.snap
  apolloschurchapp/src/tabs/discover/SearchFeed/__snapshots__/SearchFeed.tests.js.snap
  apolloschurchapp/src/tabs/discover/__snapshots__/discover.tests.js.snap
  apolloschurchapp/src/tabs/home/Home.js
  apolloschurchapp/src/tabs/home/__snapshots__/home.tests.js.snap
  apolloschurchapp/src/testing-control-panel/__snapshots__/TouchableCell.tests.js.snap
  apolloschurchapp/src/ui/LandingScreen/__snapshots__/LandingScreen.tests.js.snap
  apolloschurchapp/src/ui/Onboarding/__snapshots__/Onboarding.tests.js.snap
  apolloschurchapp/src/ui/SearchInputHeader/__snapshots__/SearchInputHeader.tests.js.snap
  apolloschurchapp/src/user-settings/__snapshots__/ChangePassword.tests.js.snap
  apolloschurchapp/src/user-settings/__snapshots__/PersonDetails.tests.js.snap
  yarn.lock
Labels: merge, ready for review

#144 Adds API Deploy instructions
  README.md
  apollos-church-api/package.json
  apolloschurchapp/.env.production
  apolloschurchapp/package.json
  package.json
Labels: merge

#143 Installed distribution certs
  apolloschurchapp/fastlane/Matchfile
Labels: merge

#147 Fixes Signing
  README.md
  apolloschurchapp/ios/apolloschurchapp-tvOS/Info.plist
  apolloschurchapp/ios/apolloschurchapp-tvOSTests/Info.plist
  apolloschurchapp/ios/apolloschurchapp.xcodeproj/project.pbxproj
  apolloschurchapp/ios/apolloschurchapp/Info.plist
  apolloschurchapp/ios/apolloschurchappTests/Info.plist
Labels: ready for review

#148 Creates Github Keychain
  .github/workflows/deploy-ios.yml
Labels: ready for review

#150 Adds Prestart Commands to Github Actions
  .github/workflows/deploy-android.yml
  .github/workflows/deploy-ios.yml
Labels: ready for review

#151 Sets CI Working Directory
  .github/workflows/deploy-android.yml
  .github/workflows/deploy-api.yml
  .github/workflows/deploy-ios.yml
Labels: ready for review

#155 Removes Terraform
  api_heroku.tf
  example.terraform.tfvars
Labels: ready for review

#158 Updated Core Algolia Instance
  apollos-church-api/config.yml
Labels: merge

#153 Uses Secret for API URL
  .github/workflows/deploy-android.yml
  .github/workflows/deploy-ios.yml
Labels: merge

#156 Removes Unnecessary Tools
  apolloschurchapp/.graphqlconfig
  apolloschurchapp/README.md
  apolloschurchapp/app.json
  apolloschurchapp/package.json
Labels: ready for review

#154 Removes Deprecated Schema Tools
  apollos-church-api/package.json
  apollos-church-api/scripts/generateLocalSchema.sh
  apollos-church-api/scripts/schemaDiff.sh
Labels: merge, ready for review

#152 Publishes Production Schema from CI
  .github/workflows/deploy-api.yml
  apollos-church-api/scripts/generateLocalSchema.sh
  apollos-church-api/src/server.js
Labels: merge, ready for review

#159 Fixes API Workflow
  .github/workflows/deploy-api.yml
Labels: merge

#161 Adds Script Helpers
  apolloschurchapp/package.json
  package.json
  yarn.lock
Labels: merge

#160 Delay the API Healthcheck
  .github/workflows/deploy-api.yml
Labels: merge

#162 Bumps version of API deploy action
  .github/workflows/deploy-api.yml
Labels: merge

#164 Fixes Storybook Build Error
  apolloschurchapp/package.json
Labels: ready for review

#163 Adds Keychain Password
  .github/workflows/deploy-ios.yml
Labels: ready for review

#165 Adds Secrets to Repo
  .gitignore
  apollos-church-api/.env.shared.enc
  apollos-church-api/.gitignore
  apolloschurchapp/.env.shared.enc
  apolloschurchapp/.gitignore
  apolloschurchapp/android/app/apollos.keystore.enc
  apolloschurchapp/android/key.json.enc
  package.json
Labels: ready for review

#167 Increases API Healthcheck Delay
  .github/workflows/deploy-api.yml
Labels: ready for review

#166 Removes False Keystore
  apolloschurchapp/android/app/apollos.keystore.enc
Labels: merge

#168 Overwrite Login Keychain
  .github/workflows/deploy-ios.yml
Labels: ready for review

#170 Adds keychain password
  .github/workflows/deploy-ios.yml
Labels: ready for review

#172 Sets up temporary keychain
  .github/workflows/deploy-ios.yml
Labels: ready for review

#173 Adds New Android Keystore Info
  apolloschurchapp/.env.shared.enc
  apolloschurchapp/.gitignore
  apolloschurchapp/android/app/apollos.keystore.enc
  apolloschurchapp/android/gradle.properties
Labels: merge, ready for review

#174 Sets up Keychain in Fastfile
  .github/workflows/deploy-ios.yml
  apolloschurchapp/fastlane/Fastfile
Labels: merge, ready for review

#175 Adds Fastlane Password
  .github/workflows/deploy-ios.yml
  apolloschurchapp/.env.shared.enc
Labels: ready for review

#176 Changed ENV Variable Name
  .github/workflows/deploy-ios.yml
  apolloschurchapp/.env.shared.enc
Labels: ready for review

#177 Adds Apple ID Password
  .github/workflows/deploy-ios.yml
  apolloschurchapp/.env.shared.enc
Labels: ready for review

#169 Moves Helper Yarn command
  package.json
Labels: merge

#178 Switched to Di Fastlane Apple ID
  apolloschurchapp/.env.shared.enc
  apolloschurchapp/fastlane/Appfile
Labels: ready for review

#180 Checkouts all commits on CI
  .github/workflows/deploy-android.yml
  .github/workflows/deploy-ios.yml
Labels: ready for review

#183 New Twilio Creds
  apollos-church-api/.env.shared.enc
Labels: merge

#182 Release 1.6-beta.1
  apollos-church-api/apollos.json
  apollos-church-api/package.json
  apolloschurchapp/apollos.json
  apolloschurchapp/package.json
  apolloschurchapp/src/content-feed/__snapshots__/content-feed.tests.js.snap
  apolloschurchapp/src/tabs/discover/DiscoverFeed/__snapshots__/DiscoverFeed.tests.js.snap
  apolloschurchapp/src/tabs/discover/SearchFeed/__snapshots__/SearchFeed.tests.js.snap
  apolloschurchapp/src/tabs/discover/__snapshots__/discover.tests.js.snap
  yarn.lock
Labels: ready for review

#181 Cleans up old files
  apollos-church-api/.dockerignore
  apollos-church-api/.envExample
  apollos-church-api/.npmignore
Labels: ready for review
