Repository ApollosProject/apollos-templates, pull requests merged in 2020-08, with the labels that each got.

#65 Dr can now pick up branch switching errors
  apolloschurchapp/package.json
  scripts/link-doctor.js
Labels: merge

#83 Release 1.5.0 beta.0
  apollos-church-api/apollos.json
  apollos-church-api/config.yml
  apollos-church-api/local.graphql
  apollos-church-api/package.json
  apollos-church-api/src/server.js
  apollos-church-api/yarn.lock
  apolloschurchapp/android/app/build.gradle
  apolloschurchapp/apollos.json
  apolloschurchapp/ios/apolloschurchapp/Info.plist
  apolloschurchapp/jest.setup.js
  apolloschurchapp/package.json
  apolloschurchapp/src/LandingScreen.js
  apolloschurchapp/src/Providers.js
  apolloschurchapp/src/client/fragmentTypes.json
  apolloschurchapp/src/content-single/DevotionalContentItem/ContentTab.js
  apolloschurchapp/src/content-single/DevotionalContentItem/__snapshots__/Devotional.tests.js.snap
  apolloschurchapp/src/content-single/WeekendContentItem/index.js
  apolloschurchapp/src/event/__snapshots__/Event.tests.js.snap
  apolloschurchapp/src/event/__snapshots__/EventConnected.tests.js.snap
  apolloschurchapp/src/index.js
  apolloschurchapp/src/tabs/discover/DiscoverFeed/__snapshots__/DiscoverFeed.tests.js.snap
  apolloschurchapp/src/tabs/discover/SearchFeed/__snapshots__/SearchFeed.tests.js.snap
  apolloschurchapp/src/tabs/discover/__snapshots__/discover.tests.js.snap
  apolloschurchapp/src/tabs/tabBar.js
  apolloschurchapp/src/ui/LandingScreen/__snapshots__/LandingScreen.tests.js.snap
  apolloschurchapp/src/ui/Onboarding/__snapshots__/Onboarding.tests.js.snap
  apolloschurchapp/src/ui/Onboarding/index.js
  apolloschurchapp/src/user-settings/index.js
  scripts/link-doctor.js
  yarn.lock
Labels: ready-for-review

#89 Deploys to Heroku via Github Actions
  .github/workflows/heroku-deploy.yml
Labels: ready for review
