Repository ApollosProject/apollos-templates, pull requests merged in 2020-06, with the labels that each got.

#19 Adds Google Cast Support
  apollos-church-api/local.graphql
  apolloschurchapp/android/app/build.gradle
  apolloschurchapp/android/app/src/main/AndroidManifest.xml
  apolloschurchapp/android/app/src/main/java/com/apolloschurchapp/MainActivity.java
  apolloschurchapp/ios/Podfile.lock
  apolloschurchapp/ios/apolloschurchapp.xcodeproj/project.pbxproj
  apolloschurchapp/ios/apolloschurchapp/AppDelegate.m
  apolloschurchapp/ios/apolloschurchapp/Info.plist
  apolloschurchapp/ios/apolloschurchapp/apolloschurchapp.entitlements
  apolloschurchapp/package.json
  apolloschurchapp/src/client/fragmentTypes.json
  apolloschurchapp/yarn.lock
  package.json
  yarn.lock
Labels: blocked

#54 Release 1.4.1
  apollos-church-api/apollos.json
  apollos-church-api/local.graphql
  apollos-church-api/package.json
  apolloschurchapp/android/app/build.gradle
  apolloschurchapp/android/app/src/main/AndroidManifest.xml
  apolloschurchapp/android/app/src/main/java/com/apolloschurchapp/MainActivity.java
  apolloschurchapp/apollos.json
  apolloschurchapp/ios/Podfile.lock
  apolloschurchapp/ios/apolloschurchapp.xcodeproj/project.pbxproj
  apolloschurchapp/ios/apolloschurchapp/AppDelegate.m
  apolloschurchapp/ios/apolloschurchapp/Info.plist
  apolloschurchapp/ios/apolloschurchapp/apolloschurchapp.entitlements
  apolloschurchapp/jest.setup.js
  apolloschurchapp/package.json
  apolloschurchapp/src/client/fragmentTypes.json
  apolloschurchapp/src/tabs/discover/SearchFeed/__snapshots__/SearchFeed.tests.js.snap
  apolloschurchapp/src/ui/SearchInputHeader/index.js
  apolloschurchapp/yarn.lock
  package.json
  yarn.lock
Labels: ready-for-review

#51 Add prayer feature
  apollos-church-api/config.yml
  apollos-church-api/local.graphql
  apollos-church-api/src/data/index.js
  apolloschurchapp/ios/Podfile
  apolloschurchapp/ios/Podfile.lock
  apolloschurchapp/ios/apolloschurchapp.xcodeproj/project.pbxproj
  apolloschurchapp/package.json
  apolloschurchapp/src/client/fragmentTypes.json
  apolloschurchapp/src/client/index.js
  yarn.lock
Labels: merge
